### PR TITLE
optimize Enhanced Chat streaming rendering

### PR DESCRIPTION
**Pull request by raefu**
Implemented because I really like the feeling of token-by-token streaming in SillyTavern.

The optimizations were implemented to make this performant on mobile.

(Ignore the first 3 commits from #36)

### CODE REVIEW

**Comment by LostRuins** [comment]
do let me know when this is ready for review

**Comment by raefu** [comment]
ready for review

**Comment by raefu** [comment]
(removed SSE because it was cherrypicked in)

**Comment by LostRuins** [comment]
After cherry picking SSE from https://github.com/LostRuins/lite.koboldai.net/commit/f25ce0e03d2f6d3043c21623213a119e67534748 and adding https://github.com/LostRuins/lite.koboldai.net/commit/bfc08bd35f05cb54b59e4e821d22339d61891045 this PR may not be needed anymore as the gametext Renderer is not used during SSE. 

Will reopen if needed. Thanks for your SSE contribution!

**Pull request closed without merging**
